# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
contracts:
  - name: UniswapV2Factory
    handler: src/EventHandlers.ts
    events:
      - event: PairCreated(address indexed token0, address indexed token1, address pair, uint256 )
  - name: UniswapV2Pair
    handler: src/EventHandlers.ts
    events:
      - event: Approval(address indexed owner, address indexed spender, uint256 value)
      - event: Burn(address indexed sender, uint256 amount0, uint256 amount1, address indexed to)
      - event: Mint(address indexed sender, uint256 amount0, uint256 amount1)
      - event: Swap(address indexed sender, uint256 amount0In, uint256 amount1In, uint256 amount0Out, uint256 amount1Out, address indexed to)
      - event: Sync(uint112 reserve0, uint112 reserve1)
      - event: Transfer(address indexed from, address indexed to, uint256 value)
networks:
  - id: 10
    start_block: 0
    contracts:
      - name: UniswapV2Factory
        address:
          - 0x0c3c1c532F1e39EdF36BE9Fe0bE1410313E074Bf
      - name: UniswapV2Pair
        address:
  - id: 42161
    start_block: 0
    contracts:
      - name: UniswapV2Factory
        address:
          - 0xf1D7CC64Fb4452F05c498126312eBE29f30Fbcf9
      - name: UniswapV2Pair
        address:
unordered_multichain_mode: true
preload_handlers: true
